### ISSUE TITLE
Update Admin View to use boathouses instead of reaches.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#113]
The admin panel should use the boathouses instead of the reaches.

The next step is to then change the front page and the flags views to be based on boathouses instead of reaches.

As a v0, hardcoding list of boathouses is fine. For a v1, it should use the `Boathouses` class in the `database.py` file as the relevant unit for manual overrides instead of reaches.

**Comment by LewisStaples** [comment]
I will work on this issue

**Comment by LewisStaples** [comment]
This is implemented in the code in my latest pull request.
