### ISSUE TITLE
Homepage for Flask-Admin updates - boating_season flag

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#122]
## Requirements:

We want the homepage for the admin panel `/admin` to have an off/on switch for the boating season flag.

Right now the boating season flag is in a config variable in `config.py` called `BOATING_SEASON`. Instead what we want is for it be in a PostgreSQL database table called "live_website_options."

The PostgreSQL table will literally be one row and one column. The single column will be called `boating_season` and the single row will be a boolean that indicates boating season. That value should be able to be changed in the admin panel's home page.

You should create a new file`flagging_site/data/live_website_options.py`. You should base it a lot after `manual_overrides.py` in my opinion. Inside that file should be a model called `WebsiteOptions` that has the `boating_season` column.

Last but not least, replace all the `current_app.config['BOATING_SEASON']` instances in the code with a `is_boating_season()` and create a method called `is_boating_season()` inside of the `live_website_options.py` file. You'll also need to `from .data.live_website_options import is_boating_season` in those files.

## Assistance:

This is not an easy task and it involves a fair amount of OOP as well. You should reference two things. First, the Flask-Admin docs https://flask-admin.readthedocs.io/en/latest/ and second, reference the code that already exists for the manual overrides stuff because you will be doing a lot of things similar to that.

**Comment by arutfield** [comment]
I'm working on this

**Comment by arutfield** [comment]
finished flask tutorials. Now for the task!
