### ISSUE TITLE
Map of boathouses

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#131]
I was looking at some of the stuff Mystic River's flagging program has. https://mysticriver.org/boatingadvisory and I really liked the map.

Can we create a map of boathouses using a tool that lets you put pins on a map? We already have geocoordinates in the database. Might be interesting to add.

**Comment by LewisStaples** [comment]
I'll work on this one

**Comment by dwreeves** [comment]
Good progress on this so far. A couple more updates and it will be perfect 🎊

**Comment by LewisStaples** [comment]
Pull request 163 has made it even better

**Comment by dwreeves** [comment]
Really like where this is right now. Closing it. Thanks so much for your work here.
