### ISSUE TITLE
Add flagging_message field to LiveWebsiteOptions

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#138]
We want to create a `flagging_message` field (varchar) that shows up inside our newly created `LiveWebsiteOptions`.

The `flagging_message` should be a message that the CRWA can put on the website about why the flags are the way they are. Here is an example:

<img width="652" alt="image" src="https://user-images.githubusercontent.com/31971762/100819700-ac555680-341a-11eb-9854-ea391d1c871f.png">

## 1. Backend and Admin Panel

(1a) Make sure `define_default_options.sql` has a default option of `NULL` inserted.

(1b) Ideally the admin panel for it should be a large text box. I think the way you implement that is here? https://github.com/flask-admin/flask-admin/blob/master/examples/sqla/admin/main.py#L205 I have no idea though.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/31971762/100820381-0f93b880-341c-11eb-82e4-52c46f47ea49.png">

## 2. Frontend

(2a) The flagging message should go here on the home page (`/`):

![image](https://user-images.githubusercontent.com/31971762/100819858-048c5880-341b-11eb-99a4-6152de3ec728.png)

(2b) It should also go into the flags widget (`/flags`):

![image](https://user-images.githubusercontent.com/31971762/100819983-41584f80-341b-11eb-8d5d-5b2f7ff8c247.png)

(2c) No need to overthink rendering it as HTML or Markdown or whatnot. Just do something like this to break newlines into paragraphs:

```python

from flask import escape
from flask import Markup

def parse_text_for_homepage(s: str) -> Markup:
    s = escape(s)
    s = s.replace('\n\n', '\n')
    s = '\n'.join([f'<p>{i}</p>' for i in s.split('\n')])
    return s
```

(2d) If the text is NULL (it's allowed to be null), then you need to treat the website as if this didn't exist.

**Comment by arutfield** [comment]
I got this

**Comment by dwreeves** [comment]
One note: you will only need to stick the `flagging_message` in one place after we consolidate the HTML/Jinja for the front page `/` and the widget `/flags`. I learned yesterday that `{% include "file.html" %}` lets you bring HTML from one place to another, so we'll be doing that soon.
