### ISSUE TITLE
Overrides by boathouse

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#145]
Instead of managing overrides super separately of the boathouses, it may make more sense to define the overrides directly in the Boathouse table.

And instead of using the existence of a row as showing the existence of an override, the overrides would be defined with a true/false flag. All overrides would be contemporaneous.

So the admin interface would look kind of like this for the overrides, but I'd still separate out the Boathouses table into two separate views: one for CRUD operations more generally, and one _only_ for editing the flags (no ability to create or delete rows or edit metadata for the boathouses).

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/31971762/101994844-ac174f80-3c93-11eb-8d8c-2d704f2c8f82.png">

Then, we would create an event based way of tracking changes to manual overrides.

Examples here:

- https://stackoverflow.com/questions/13785855/how-to-log-data-change-in-postgresql
- https://stackoverflow.com/questions/50166268/how-would-you-track-the-history-of-all-crud-operations-without-re-architecting/50166380

That said, it's probably better to do it through SQLAlchemy: https://docs.sqlalchemy.org/en/13/orm/session_events.html

The reason I want to do this approach is twofold. First, I think it's a good schema. Second, I don't think the CRWA will end up using our current approach of defining start and end dates in a meaningful way to record historical changes to the river status, so it'd be better to just use events to log.

---

As a note, this is a very advanced feature, both to implement and maintain. So we want to meet the following two requirements:

1. the website should operate perfectly fine even if this functionality breaks for some reason, and
2. the code to implement this should not warp the rest of the code base around it; it should sit off to the side basically.

**Comment by LewisStaples** [comment]
I'll work on this one

**Comment by LewisStaples** [comment]
The latest pull request includes overrides in the boathouse table
