### ISSUE TITLE
Add "Boathouses" tooltip to detailed outputs page.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#146]
Right now the table just says the reaches but not the boathouses. We should add some sort of thing under the tables, or above the tables and under the headers, that just shows the boathouses.

I think a tooltip would be best next to an SVG "info" icon. Tooltips: https://www.w3schools.com/css/css_tooltip.asp

Use an SVG for the info icon: https://iconmonstr.com/info-6-svg/ Add it to the website the same way we handle the other SVGs.

Lastly, don't manually encode the boathouses.

**Comment by arutfield** [comment]
I got this
