### ISSUE TITLE
Use flask-static-digest

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#150]
TLDR: read the readme here, make the requisite changes to the Jinja template and the `create_app()` functions. https://github.com/nickjj/flask-static-digest There is a good youtube video explaining what this is and why it's useful.

**Comment by arutfield** [comment]
I got this

**Comment by dwreeves** [comment]
Did some more research into it. I think this might be better for our particular use case? https://github.com/evansd/whitenoise

The issue seems to be that the setup in the `flask-static-digest` setup is for Nginx. It might not work on non-Nginx servers, and we're not using Nginx right now.

There are three possible options for this task:

1. We serve the website in Heroku as it currently is, using `flask-static-digest`.
2. We serve the website in Heroku as it currently is, using `whitenoise`.
3. We serve the website in Heroku using Nginx, using `flask-static-digest`.

Can you look into it a bit for me and see what the best option is? My feeling is option 2 is the better option. We'd lose the md5 hashing but that's not a huge deal; the gzipping is the more important thing.

Some questions to answer to help solve the question of which of the three approaches should we use:

- Does Flask-Static-Digest's approach work outside of Nginx? Or is it Nginx only?
- How good of an idea is it to setup a Flask + Nginx + Gunicorn configuration in Heroku?
  - How hard is it to do?
  - How well does Heroku support it?
  - What are the benefits?

Sorry I don't really know what the best solution here is, I'm not a real web developer... 😬

**Comment by arutfield** [comment]
Unfortunately I'm not a web developer either.
Adding Nginx + Gunicorn seems like trying to add a lot in a short period of time. 1 would be ideal, as it's the least changes, but I'm not convinced it's been thoroughly tested on anything but Nginx. There don't seem to be any examples. What are we using for a web server now?
2 seems the most straightforward. There's even a tutorial here: http://whitenoise.evans.io/en/stable/flask.html

**Comment by arutfield** [comment]
Heroku should work with Nginx and Gunicorn. No idea how difficult it is as I've never worked with either before.

**Comment by arutfield** [comment]
On the other hand, it says whitenoise isn't as great unless you use a CDN. Does Heroku count as  a CDN?

**Comment by dwreeves** [comment]
Heroku doesn't have a CDN by default. There are plugins for it, but it
would be overkill and I think we're at our plugin limit for Heroku free
tier.

This stackoverflow post says: https://stackoverflow.com/a/50345514

> The downside of WhiteNoise is that if you use it without a CDN like
Cloudfront or Cloudflare it will definitely not perform as well as nginx.
WhiteNoise is best either when used with a CDN (as most production sites
ought to be doing) or for low-traffic sites where ease of configuration
trumps performance.

It's possible that maybe what we should be using is Gunicorn + Nginx, then?
I found this snippet-- maybe this is what we want?
https://medium.com/@eserdk/heroku-nginx-gunicorn-flask-f10e81aca90d It
looks like the step I'd need to test out is adding a Nginx "buildpack,"
which I can do on our staging server. Alternatively if you have your own
setup for Heroku you can try this yourself.

**Comment by dwreeves** [comment]
Heroku doesn't have a CDN by default. There are plugins for it, but it would be overkill and I think we're at our plugin limit for Heroku free tier.

[This](https://stackoverflow.com/a/50345514) stackoverflow post says:

> The downside of WhiteNoise is that if you use it without a CDN like Cloudfront or Cloudflare it will definitely not perform as well as nginx. WhiteNoise is best either when used with a CDN (as most production sites ought to be doing) or for low-traffic sites where ease of configuration trumps performance.

It's possible that maybe what we should be using is Gunicorn + Nginx, then? I found this snippet-- maybe this is what we want? https://medium.com/@eserdk/heroku-nginx-gunicorn-flask-f10e81aca90d It looks like the step I'd need to test out is adding a Nginx "buildpack," which I can do on our staging server. Alternatively if you have your own setup for Heroku you can try this yourself.

**Comment by dwreeves** [comment]
Another thing to look into. https://pythonhosted.org/Flask-Caching/ This does server-side caching. Ideally we'd cache the `/flags` page, which will be hit the most often, and this avoids doing repeated calls to the SQL database for data that doesn't change often. Then we can just clear the cache after every database update. Seems a bit tricky to implement cleanly but seems like a huge boost to performance.

**Comment by dwreeves** [comment]
I think we're pretty good on this. We'll forget about gzipping, the caching has been a huge performance upgrade. And I already have a solution for MD5 hashing using query params.

**Comment by dwreeves** [comment]
See #159 for more on caching.
