### ISSUE TITLE
Batch job for overrides

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#156]
We want to be able to turn off/on the manual overrides by reach OR all the boathouses at once, using a batch job: https://stackoverflow.com/questions/35852255/flask-admin-batch-action-with-form

Separately but relatedly, we also want to be able to filter by reach: https://flask-admin.readthedocs.io/en/latest/_modules/flask_admin/contrib/sqla/filters/

**Comment by arutfield** [comment]
I got this

**Comment by arutfield** [comment]
If I run the example from the flask-admin git repo, I can see filter examples
