### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#17]
Here's a guide on running a Flask app in HTTPS without self-signing the cert. https://blog.miguelgrinberg.com/post/running-your-flask-application-over-https

Right now deployment is just the stuff mentioned in the README, and it deploys HTTP. Can we create a deployment script that embeds real SSL cert stuff in the deployment of the application and get it running over HTTPS? (Use `vault.zip` if necessary to store anything sensitive as needed.)

**Comment by edsun123** [comment]
Gonna take a look at this.

**Comment by dwreeves** [comment]
Hold off a second on this. It's possible Heroku has a better and simpler solution to this.

**Comment by edsun123** [comment]
Reading and trying things out in https://devcenter.heroku.com/articles/ssl-endpoint

**Comment by edsun123** [comment]
Given the CRWA might be looking into hosting free, using wildcard certificates is best and available to any free heroku account,

**Comment by edsun123** [comment]
Resolved. There might be options for third-party certificate. Try lets's encrypt otherwise Heroku provides wild card *heroku.app cert.
