### ISSUE TITLE
Convert Yaml to Json

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#2]
We agreed that it is more appropriate to convert the YAML stuff into JSON. Here are the steps required to do that:

- Replace any `import yaml`'s with `import json`, and replace all other relevant functionality.
- Make sure it's also not mentioned in docstrings or comments.
- Replace `keys.yml` in the vault with `keys.json` with the same values. Rezip the file using ZipCrypto encryption and using the same vault password.
- Remove PyYaml from `requirements.txt`
- Replace `keys.yml` in the gitignore with `keys.json`.
- _Test that the website still works normally._
- Most importantly of all are not the dos, but rather the don'ts: **do _not_ commit an unencrypted zip file to Github** and **do _not_ leave the keys file outside of the zip file.**

**Comment by edsun123** [comment]
Should be resolved. Merged last week.
