### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#20]
Turn the model output into a RESTful API. We will want to do this eventually to assist in integration with the CRWA's Weebly site.

Here are the steps:

1. Define an appropriate schema for the JSON output.
2. Make the model output according to that schema.
3. Stick it on the website.

There are three ways to do this:

- **The bare-bones solution: output a dict of the values with `flask.jsonify`.** I would probably go with this approach for a MVP of a RESTful API. It won't enforce a lot of the formalities of a RESTful API but that's OK.
- **Use Flask-Restful.** Note that this library is _not_ directly affiliated with the team that manages Flask, and for whatever it's worth the creator of Flask is not a huge fan of it. Still, it's a pretty popular solution, and does enforce a lot of the formalities of the RESTful specification.
- **Use FastAPI**. This is a newer framework, but it's extremely powerful and is already one of the most popular frameworks for web APIs in Python. In a vacuum this is my preferred solution. It does require use of a WSGI middleware dispatcher (Werkzeug has one) but I don't believe this is a big deal.

**Comment by dwreeves** [comment]
Update on this: the FastAPI suggestion is impractical and silly when I rethink about it. FastAPI is great, but I don't think it makes sense to implement basically a whole different web framework on top of our app.

I think the "bare bones solution" is the best approach, but in addition we should implement semi-automated documentation using a framework like [flasgger](https://github.com/flasgger/flasgger).

**Comment by edsun123** [comment]
Going to start this.
