### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#22]
We have a start on documentation. What we want to do is eventually get our docs to the point where we can deploy them through `mkdocs`: https://www.mkdocs.org/

I suggest mkdocs because the other major framework for docs, Sphinx, is better suited for Python library (i.e. it's really good at pulling in your docstrings and inspecting your code using an AST to document a library). But it's not necessarily ideal for something like a Flask website. Also, mkdocs uses Markdown, which is something we're already using and it's also a more familiar framework to most compared to RST (which is what Sphinx uses).

---

To set up a `docs` folder, we need actual content that should go in it. I already have a comprehensive instruction guide on how to deploy the site that I'm looking to put up soon. Can we brainstorm and think of anything else we need? To note: the docs folder should include stuff related to how the website works, not development of the website (that's what the Wiki is for). Imagine the intended audience as someone who comes across the repository and wants to know how the site works and how to set it up, but doesn't care so much about making changes to it.

**Comment by edsun123** [comment]
Addition of MKDocs has been added today. To deploy, host it in github pages. Check https://www.mkdocs.org/user-guide/deploying-your-docs/.

**Comment by dwreeves** [comment]
Closing this issue because we have a good baseline to work with, BUT there's still more to be added in the docs, just as a note.
