### ISSUE TITLE
Translate old template into Jinja and connect it

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#3]
The old template is available [here](http://notification.crwa.org/wqmodel/charlesflags.php). We should make sure that this has a Jinja template equivalent for our own website, and then we should connect it to the model.

I believe this should be the root directory of the website, i.e. `bp.route('/')` in `blueprints/flagging.py`. Discuss if you believe it should be something else.

**Comment by bxchang04** [comment]
I'm working on this :)

**Comment by bxchang04** [comment]
just submitted pull request tonight

**Comment by dwreeves** [comment]
Pull request accepted. I will keep this issue open because we still have a few more modifications we'll want to make to the template (more formal/modern stylizing and resizing the flags), but your work in getting the flags to render for each reach means we're more than half-way there. Excellent work Ben!

**Comment by bxchang04** [comment]
new pull request submitted
