### ISSUE TITLE
Clean up home page

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#31]
- Put the flags in a table with the following two columns
   - Reach, with bullet points underneath for each boat house within the reach.
   - The flag
- Underneath the table should be a "Last Updated," which should take the _latest timestamp_ in the preprocessed dataframe from `get_data()`.
- Add some headers:
   - Overview
   - Water Quality Today
- Copy and paste some language from here: https://www.crwa.org/flagging-program.html and cut down on some of the older language.

**Comment by bxchang04** [comment]
I can take care of this!

**Comment by bxchang04** [comment]
just submitted pull request :)

**Comment by dwreeves** [comment]
Front page is pretty tidy now with Ben's improvement.

We still have some UI challenges to overcome, but it's not related to the content on the front page, which is well done; it's related more to the website template in general.
