### ISSUE TITLE
API landing page

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#33]
Right now the API link goes straight to the `api/v1/model`. But it really should be a landing page where we link to (multiple) APIs.

Add a new blueprint called `blueprints/api.py`. It should have a default prefix of `/api`. Move the API code from `flagging` to `api` and route it to that blueprint as `/v1/api`.

Add a new file: `/templates/api/index.html`. On this page, provide some information about the API. Not sure how to do this? Look at some examples:

- https://www.bls.gov/developers/
- https://developer.spotify.com/documentation/web-api/
- https://www.petfinder.com/developers/

Add a note to the API landing page in bold that the `v1` API is still tentative and under development, and that the `v1` API will be finalized when this message is removed.

Eventually we will add three more APIs to facilitate the public availability of the CRWA's data. Adding these is _not_ required for this issue; we'll tackle this later. But just so you have an idea:

- HOBOlink API: Basically the output from `get_hobolink_data` but as a JSON.
- Preprocessed data API: Basically the dataframe we pass through all the models.
- Metadata API: Information about the reaches. List of the boathouses within each reach and geocoordinates of the boathouses.

This will make 4 APIs total.

API documentation for each of the 4 APIs individually should be done through something like Flasgger, and that will be a separate issue.

**Comment by dfe325** [comment]
Taking a look at this.

**Comment by dwreeves** [comment]
Finished! #41 and #40
