### ISSUE TITLE
Automated documentation of the API through Flasgger

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#34]
Mostly self explanatory: https://github.com/flasgger/flasgger Plug this into our API and the website. The readme is extremely comprehensive and covers the `flask_restful` use case.

**Comment by edsun123** [comment]
Want to take a look into it.

**Comment by edsun123** [comment]
Currently since the api is in progress, documentation is tentative. (reminder: must change the yaml for class reach_api in the future)

**Comment by edsun123** [comment]
For reference: 
https://github.com/swagger-api/swagger-ui/issues/2757 (operations is not defined if yaml is not readable) 
https://github.com/flasgger/flasgger/issues/185 (blue995 gives a good example of using flasgger on blueprint)
