### ISSUE TITLE
iframe of flags.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#35]
We need a widget that connects to our RESTful API. The widget should be standalone and should be able to run on their Weebly website, which doesn't allow for any client-side scripting.

The easiest way to do this is with a tiny web page designed to fit in an "iframe"; I would suggest doing this to start.

Check out what they're currently doing here: https://www.crwa.org/flagging-program.html It seems they want to show these flags by boathouse and not by reach, so make sure you do that. They also want a time last updated value.

Also, make sure to add actual code for the iframe so they can just stick it inside of their Weebly website.

Make sure both the iframe _and_ the page rendered inside of the frame are "responsive," i.e. able to handle changes to the size of the web page.

**Comment by edsun123** [comment]
I can take a look at this.

**Comment by edsun123** [comment]
![Screen Shot 2020-07-27 at 9 24 04 AM](https://user-images.githubusercontent.com/34005715/88546884-fd77b880-cfea-11ea-9404-bc0f61b88a6d.png)

**Comment by dwreeves** [comment]
We got reaches!

Reach 2:
- Newton Yacht Club
- Watertown Yacht Club
- Community Rowing Inc.
- Northeastern’s Henderson Boathouse
- Paddle Boston at Herter Park

Reach 3:
- Harvard’s Weld Boathouse

Reach 4:
- Riverside Boat Club

Reach 5:
- Charles River Yacht Club
- Union Boat Club
- Community Boating
- Paddle Boston at Kendall Square

**Comment by edsun123** [comment]
Super helpful!

**Comment by dwreeves** [comment]
Status on this: I'm going to pull Edwin's PR in once Lewis is done with the merge of `dev` and `dev_postgres` resolution. I think there are a few changes I'll have to make to Edwin's PR to accommodate the changes since he started it but it's a good baseline that fulfills all the base requirements.
