### ISSUE TITLE
Parameterize model displays.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#4]
Let's make our table outputs more sophisticated.

### Requirements

In `blueprint/flagging.py`, make it so `./model_output` can take two optional parameterized URL inputs: `reach` and `hours`.

- Reach is an int between 2 and 5. If `reach` is None, return all the models. Else, just return the one defined by the reach parameter.
- Hours is an int between 1 to 48. If hours is None, the default should be 24.
- Bad inputs should raise a 400 status code with `abort(400)`. See the [Flask documentation on error handling](https://flask.palletsprojects.com/en/1.1.x/errorhandling/) for more.

### Examples

`http://127.0.0.1:5000/model_output` should return the same thing it currently does.

`http://127.0.0.1:5000/model_output?reach=4&hours=36` should output 36 hours worth of reach 4's data.

### Notes

- Try not to branch the logic out. You can still use the `'<br /><br />'.join(list(map(styler, list_of_dataframes)))` logic all the same for 1 or 5 tables.
- Don't run functions for tables we won't be using. E.g. if the user wants reach 3, then only run the table for reach 3.
- Eventually this will likely be used for a button/link next to each flag that says "view details" where it will show the last 24 hours for that particular reach.

**Comment by edsun123** [comment]
Working on it. Almost finished.

**Comment by edsun123** [comment]
Resolved. Been merged last week.
