### ISSUE TITLE
Merge `dev2` into `dev_postgres`

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#47]
Right now, `dev_postgres` hosts an MVP of the Postgres database, but it was developed in a separate context of a lot of other things, and it's fallen behind of some changes we know we're going to have in the website eventually. So we want to merge `dev2` into it (which contains the most up-to-date version of the website).

The end goal with merging `dev2` into `dev_postgres` is not to fix every single problem with `dev_postgres` and make the website have a fully functional postgres database. The goal is simply to merge it in and resolve merge conflicts where they exist. The rule for resolving these merge conflicts is:

- preserve basically everything in `dev_postgres` that references a database or `db`.
- preserve `dev_postgres`'s behavior of running the home page through the Postgres db.
- preserve `dev2`'s behavior of separating the API out into a separate file.
- preserve `dev2`'s front-end changes.

**Comment by LewisStaples** [comment]
I will take a look at this issue

**Comment by LewisStaples** [comment]
Note to self .... per our discussion, the merge will instead be between dev_postrgres and dev (instead of dev2)
