### ISSUE TITLE
`dev_postgres`: Parametrize `latest_model_outputs` function to return between 1-48 hours of data.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#49]
Right now it only returns 1 hour. However it needs to return between 1-48 hours.

There are a lot of ways to do this.

### Approach 1

One way is a pure SQL approach and select a variable number of hours. Parametrize using `%s`. You would also have to modify the signature of the SQL query-running functions to accept optional parametrization. So instead of:

```python
def execute_sql_from_file(file_name: str):
```

you'd want this instead:

```python
def execute_sql_from_file(file_name: str, parameters: Optional[list] = None):
```

I'll let you figure out the rest. But in any case, do not delete the query that retrieves the _latest hour_ worth of data. You want two queries side by side. The reason why is because I believe there is no way to optimize the flexible `N >=1` query to run as quickly as the strict `N == 1` query, and there are a _lot_ of contexts in which we want `N == 1` (i.e. the home page and the iframe). We're not optimizing this site for pure performance, but there's also no reason to make the site slower for no good reason.

### Approach 2

Simply hard-code the max number of hours to return, i.e. 48, create something like a `return_48_hours_of_model_outputs.sql`, and then do the filtering _in Pandas_. In a corporate environment with tons of fleshed out engineering, tons of engineers paid 6 figures to maintain the thing, and millions of rows that need to be processed efficiently, this solution is worse than Approach 1. But we're not designing code in that context! In _our_ context, there are a lot of reasons why this solution is perfectly fine and arguably preferable. That said, I'll leave it up to you which you prefer.

**Comment by LewisStaples** [comment]
I'll take a look at this one

**Comment by LewisStaples** [comment]
The code I submitted earlier today implements the requested functionality
