### ISSUE TITLE
`dev_postgres`: Modify every data call to retrieve the data from the Postgres DB.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#50]
There are currently 3 places (will eventually be 4 places) where we call the data and model outputs:

1. The home page
2. The detailed outputs page
3. The RESTful API
4. [NOT YET IMPLEMENTED] The iframe body

The goal of this task is to make it so all the data that gets called to the frontend does so through the Postgres database in these 3 (eventually 4) locations.

Note that #49 is a blocker for this issue and would need to be done first or in conjunction with this issue.

**Comment by LewisStaples** [comment]
I'll take a look at this one

**Comment by LewisStaples** [comment]
The code I submitted earlier today implements the requested functionality for the detailed outputs page (the functionality had previously been implemented for the home page)

**Comment by LewisStaples** [comment]
This requested functionality for the RESTful API has been implemented and submitted
