### ISSUE TITLE
`dev_postgres`: Make documentation (README) surrounding the database better.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#51]
Right now I just very lazily stuck some notes at the bottom of the README. Let's get that house in order.

- README:
  - Tell developers they need to install Postgres as a prerequisite to run the site.
  - Put initiation of the database as part of the setup, not at the bottom of the README. Setting up the database should not be its own section in the README.
- Add a `database.md` guide to the `/docs` folder.
  - Tell them how to install Postgres (provide a link to the download instruction page), and tell them that they need to add Postgres to their system PATH, etc. all that basic setup stuff.
  - Be more detailed about what's going on here: In the README, just tell the reader what to do; in the docs, _explain_ to the reader what is _happening_ with each step.
  - Explain what is happening with `flask init-db` and `flask update-db`.
  - Try to incorporate your own troubles setting up the database and add some troubleshooting tips that helped you if you had any issues.

**Comment by edsun123** [comment]
I will write up a readme as I'm working on it.

**Comment by dwreeves** [comment]
Status on this: We have a pretty good baseline in `database.md`. Not perfect, but that's fine for a lot of reasons: rough drafts / outlines are half the work, and also the database isn't even done yet so it's hard to document something that isn't done.

I'll keep this issue open because it's not 100% but I would not worry about it for now, so I'll mark as "low priority."

I've taken the mantle of updating the docs; I have a WIP version here: https://dwreeves.github.io/flagging
