### ISSUE TITLE
`dev_postgres`: Add Postgres database to the test environment.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#52]
First, before you tackle this issue, study how the database works and how it gets set up!

I recommend that if you want to tackle this issue, you should also tackle #51 in conjunction, just so you have a very clear understanding of what's going on.

Once you have that understanding of what's happening, make sure we can actually replicate the database setup process in the test environment. This might require a few things, including:

- editing the `app` fixture to init the database
- possibly creating a new fixture related to the database.
- Editing `TestingConfig` to have new values that would not conflict with any existing development database.
- you may be required to set up a _separate_ and _isolated_ test database that does not conflict with the development version of the database.

I'm not really sure what the best practice is for testing a Postgres database in Flask, but you should at least try to get an understanding of how the Flaskr tutorial does its tests: https://github.com/pallets/flask/tree/master/examples/tutorial Note that SQLite is a file-based SQL database, not memory based. And note how in the tutorial they create a separate temporary directory for the test database. In our case we can't do _exactly_ that because Postgres isn't file-based. But the concept of isolating the test environment _is_ what we want to do. So find out how to do that in the context of Postgres!

**Comment by edsun123** [comment]
Since I'm doing the documentation #51, I might have to do this. I probably tackel this on perhaps next week or whenever I finish the heroku issue #54.

**Comment by edsun123** [comment]
This issue is open for anybody.
