### ISSUE TITLE
`dev_postgres`: Figure out how to use the task scheduler to update database.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#53]
Right now a lot of the ground work for this has been laid out. There is a CLI function available:

`flask update-db`

So Heroku could just run that on a cron and we're set!

However, right now I don't have it so Heroku would be able to run that on a cron! Can you make it so the website can do that? Use Heroku's own task scheduler to do this: https://devcenter.heroku.com/articles/scheduler If it involves any files or code that Heroku reads, commit them in. If it involves some set-up, add a doc to the `/docs` folder explaining the setup required, or modify the `deployment.md` file to include that setup as part of the deployment.

For this and other Heroku-related tasks, create your own staging environment for the app using your own Heroku account (it's free if you don't have one!) and try to make it work on your own deployment of the app.

**Comment by dfe325** [comment]
I'll take a look at this.

**Comment by edsun123** [comment]
I can also contribute because I am also looking at heroku.
