### ISSUE TITLE
Add test of REST API in a `test_api.py` file.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#56]
Basically just run the client fixture, do a `get` request, and assert that the inputs and outputs are what you expect them to be.

- `test_model_output_api_schema()` should test that the `keys` are a particular way and the `values` are of a particular type.
- `test_model_output_api_parameters()` should test that `hours=10` returns 10 rows of data, that setting the reach returns only that reach.

The test func names are long to accommodate the name-space when we additional APIs we'll add to this file, and we'll be testing their parameters and schemas as well.

**Comment by dfe325** [comment]
I'll take a look at this.

**Comment by dfe325** [comment]
First pass on this issue here: https://github.com/codeforboston/flagging/compare/dev2...dfe325:dev2 

Tests don't work as of yet, need to do some fiddling but just wanted to make sure I'm on the right track. Have to step away now but will be working on this later today. Thx

**Comment by dwreeves** [comment]
Good job so far.

Re the first one: Right idea, but I'd do it more explicitly like this:

```python
schema = {
    'some_key': str,
    'some_other_key': list
}

res = some_api_function()
for key, val in res.items():
    assert key in schema
    assert isinstance(val, schema[key])
```

This is a far less cryptic way to present the problem because you can see every single thing that's being tested against with your own two eyes; it doesn't hide anything.

In Python, `assert type(obj) == some_type` is less preferable compared to `isinstance(obj, some_type)` in the majority of contexts. `isinstance` takes into account inheritance, and in Python a subclassed object is considered to be OK. (That's what the whole duck-typing thing is about.)

Small note: Docstrings use triple-double quotes, not triple-single quotes. https://github.com/codeforboston/flagging/wiki/Code-Style-Guide#1-use-pep-8 `As per the Google Style Guide however, we still use 3x double quotes for docstrings.`

Re: the second one:

The point of this sort of test is to test that the input-output relationship is what we think it should be. Right now you have no inputs, though.

Also, I prefer `len(df)` to `df.shape[0]` because it looks more like normal python so it should be easier for people to read.

**Comment by dfe325** [comment]
Ok, took [a second pass](https://github.com/codeforboston/flagging/compare/dev2...dfe325:dev2). 

* Docstrings to 3 “s
* df.shape[0] changed to len(df)

This currently doesn't pass one of the tests, it returns a string when it should return a list. I tweaked the code you gave to parse what looks to be a pretty complicated dictionary/dictionary of lists coming out of the get request... not sure if  model_api() is the right way to go, which might explain it.

**Comment by dfe325** [comment]
Update: Got the last test to work but it's super ugly. Will be working on refactoring tonight.

**Comment by dwreeves** [comment]
This is still open because `test_api.py` doesn't work.

**Comment by dwreeves** [comment]
Done!
