### ISSUE TITLE
Add new config option `API_MAX_HOURS`, put it in the REST API, and test its behavior.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#57]
Three tasks, but all related.

- Add `API_MAX_HOURS` to the Config. Add a docstring below it to explain what it is. Here's a docstring for you: `"""The maximum number of hours of data that the API will return. We are not trying to be stingy about our data, we just want this in order to avoid any odd behaviors if the user requests more data than exists."""`.

- Make sure the REST API and the `output_models` page both use this config parameter.

- Create a `test_api.py` file (or if it already exists by the time you do this, add onto it). In that file, test that the max hours param works with a function called `test_max_hours`. Here's how to test it: Assert that if you try to do MAX_HOURS + 10 hours as the param, that the returned JSON from the API return MAX_HOURS instead.

**Comment by cameronreaves** [comment]
Working on this issue
