### ISSUE TITLE
Test that the code properly handles multiple columns

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#58]
Related to issue #37, I want a test that says the code can handle the weird erroneous `.csv` in that particular issue:

![image](https://user-images.githubusercontent.com/31971762/86862165-aab77a80-c096-11ea-90ce-7be4444cdf18.png)

I already know that the code can handle this situation. I want to enshrine it as a test case, though.

Conceptually this test is very simple: when `request_to_hobolink` returns this horrific csv, we assert that the function `get_live_hobolink_data` still returns a valid Pandas Dataframe. In this case we want to simply assert that the Pandas Dataframe is equivalent to the Pandas Dataframe it currently outputs.

The way we have to do this is to mock `request_to_hobolink` so that it returns the cursed csv in the context of this particular test, and then inside of the test we run `get_live_hobolink_data`.

Here's a bit of info on how to mock stuff in Pytest: https://docs.pytest.org/en/stable/monkeypatch.html

The horrific CSV is here: https://gist.github.com/dwreeves/73771a735f7ff9262ed779ae78199b28

I would place the csv file and a pickled version of the dataframe we're testing against in a new folder, `/tests/static`.

**Comment by bancona** [comment]
I can try this one
