### ISSUE TITLE
Add a SQL database that stores Hobolink, USGS, and model predictions.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#6]
We want to store our data in a SQL database eventually.

Don't worry about getting it all connected to the models and requests for now; don't worry about functions that explicitly write to the database or retrieve data from the databases. Just worry about how to get a database set up and make it so the Flask app recognizes that it exists. (Not necessary but for bonus points: make it so that it can run offline too, similar to how `get_keys()` works both when online and offline.)

[Read this document carefully.](https://flask.palletsprojects.com/en/1.1.x/tutorial/database/) You should be doing everything in that doc. Except we are going to do two things differently: first and most dramatically, we'll be using Postgres instead of Sqlite. (Long story short: Postgres is better for Heroku apps.) Second, our file will be called `database.py`, not `db.py`.

If you get to the point where you're initializing a real database and need the table schemas:

Hobolink and USGS schemas are as-is, in tables called `raw_hobolink` and `raw_usgs` respectively.

There should be a table called `ecoli_predictions`. The schema should be `timestamp` and then `r2_probability` `r3_probability` etc. and `r2_safe` `r3_safe` etc. all as columns.

**Comment by LewisStaples** [comment]
I am reviewing this issue

**Comment by dwreeves** [comment]
You and @dfe325 should collaborate, I think he is also working on it.

**Comment by dfe325** [comment]
👍 Lewis, I’m reading through the docs tonight, will Slack you in the next day or so to collab, lmk if you make any progress in the meantime

**Comment by LewisStaples** [comment]
Dan Eder ... Here's where I am now.  I've read through the notes.  My next step is that I'll need to install postgres on my machine.  I'll look forward to chatting on the slack

**Comment by dwreeves** [comment]
We have a very basic Postgres database now. I'm going to close this issue and open up more specific issues relating to it using a new tag called "Postgres"
