### ISSUE TITLE
`dev_postgres`: Automate database creation

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#60]
Right now the.

- Create a CLI called `create-db` that extends the Flask app. See the `init-db` CLI for an example of how to do that. I suggest following that pattern pretty closely.

- The `create-db` CLI should call a function in `database.py` called `create_db()` that automates the procedures in the README. Do not use `subprocess` module; that's cheating. Let's use psycopg2 to do this.

- Use the `current_app.config` params to create the database; i.e. don't hardcode `flagging` as the database name, don't hardcode the host and the port, etc.

Behaviors:

- `create-db` should create the database and a `flagging` superuser if the database doesn't exist. The database it creates should be completely empty (populating the database is what `init-db` will do; these functions should not overlap).
- `create-db` should not do anything if the database already exists.
- I should be able to run in the command line `flask create-db`.
- `create-db` should ask the user to set the `flagging` admin password; default value should be the `POSTGRES_PASSWORD` env variable. Check the CLI in the `data/_store` table for how to do that, and also check this page out: https://click.palletsprojects.com/en/7.x/options/
- Don't worry about this for now but: Ultimately we need to be able to one-click deploy to Heroku like this: `heroku config:set POSTGRES_PASSWORD=some_password_here` then `git push heroku master` without it ever prompting us for the password so long as `POSTGRES_PASSWORD` is defined in the environment.

**Comment by LewisStaples** [comment]
I'll take a look at this one

**Comment by LewisStaples** [comment]
The requested functionality has been submitted.  Note that it was agreed after the issue was created to exclusively use the postgres super (in other words we agreed to omit the flagging superuser)
