### ISSUE TITLE
Add unit tests for Flask website.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#7]
If you haven't already, go through the "Flaskr" tutorial. Then after you're comfortable with it, check out its unit-tests [here](https://github.com/pallets/flask/tree/master/examples/tutorial/tests) Copy as much as is relevant inside the `conftest.py` file and start writing a unit test that tests the website called `test_site.py`.

**Comment by dfe325** [comment]
Working on this

**Comment by dfe325** [comment]
submitted a draft PR with comments! one test passes, one doesn't
