### ISSUE TITLE
`dev_postgres`: Add API endpoint called `boathouses` that returns all boathouse metadata.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#75]
[Perform this work in `dev_postgres`]

Just `select * from boathouses order by reach, name` and return that as array of dicts. I think you want to do something like:

`return {'boathouses': df.to_dict(orient='records')}`

Right now the API stuff is in `dev2` but the OpenAPI schema is in `dev2`. So we also need someone to work on #47. Any takers?

**Comment by LewisStaples** [comment]
I'll take a look at this one

**Comment by LewisStaples** [comment]
Per discussion .... all boathouse information shown on the homepage is currently hardcoded .... Change the program to use boathouse data in the database
