### ISSUE TITLE
Add unit tests for data / models.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#8]
The unit tests for the models should be in a file called `./tests/test_data.py`. The tests should assert that the predictions are between 0 and 1. Write tests in the `pytest` idiom. There are more things we can test down the line as it pertains to models and data, but this is a good starting place.

**Comment by bxchang04** [comment]
I can work on this this week :)

**Comment by cameronreaves** [comment]
hey I can write tests for test_data.py, it seems this issue hasn't been closed

**Comment by dwreeves** [comment]
**UPDATE:** We have some tests done, but they're only testing for one very specific behavior of the data, which is that the live data is current as of the last 60 minutes. Check out the `dev2` branch as a baseline to build off of for the tests. We still need to test:

- that the _combined_ USGS + Hobolink data is recent as of the last 2 hours.
- that the models themselves output a value between 0 to 1 for the probability.

**Comment by dwreeves** [comment]
I think we have some pretty good unit-tests. Not totally comprehensive but I think we'll revisit when our code is tidier.
