### ISSUE TITLE
`dev_postgres` Exception handlers

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#81]
For this task, work off of Bertie's branch relating to the flask-admin page, and merge it to `dev_postgres`.

Check this: https://flask.palletsprojects.com/en/master/errorhandling/

We want to add an exception handler for both 404's and for AuthExceptions. What I would do is stick it in a function in `app.py` called `register_error_handlers`. The `register_error_handlers` function should take only one positional argument, the app instance. Inside of that function, define your error handlers roughly like this:

```python

def register_error_handlers(app: Flask):
    @app.errorhandler(SomeExceptionHere)
     def handle_some_exception():
        return render_template('error.html', header='404', msg="This page doesn't exist!")
```

So, in addition to writing these functions for 404's and AuthExceptions, you also have to define a template that handles errors. I suggest the above solution I printed out which is: create a template called "error.html" that passes in two arguments, a header and a message. That way we don't need a bunch of templates for errors and it makes the app's code both more compact and more scalable down the line.

**Comment by bancona** [comment]
I'll take a look at this

**Comment by danivalades** [comment]
I'll work on this

**Comment by dwreeves** [comment]
Clarification: We already handle auth errors, and normal users should never see auth errors, so we don't need a handler for that.

However, we don't handle 500 errors. We want to log the 500 errors in the app, and present to the user an "Oops, something went wrong" sort of message.
