### ISSUE TITLE
Add code examples in `/api/`.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#82]
Add an example of how to query the API in Python and in R. Use the Pandas library and Tidyverse respectively.

Use syntax highlighting in your examples. You need to hook a CDN that has a syntax highlighter into `/api/index.html` and then wrap the code example in an element within the CDN.

**Comment by LewisStaples** [comment]
I'll take a look at this issue

**Comment by LewisStaples** [comment]
The requested functionality is now submitted
