### ISSUE TITLE
Notification on front page if website is not updating

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#97]
Use the `flash` to notify if the database hasn't updated in at least 72 hours: https://flask.palletsprojects.com/en/1.1.x/patterns/flashing/ Send this notification in the front page.

The message should be: `Note: The model is currently offline.`

I do not believe the "Flash" object has been set up in the frontend. You need to modify `base.html` to include it. The flash should occur below nav but above the content block. I believe the background color should be `#ffff6f`.

Use the documentation above and the "Flaskr" demo to get a sense of how to do some of this.

**Comment by LewisStaples** [comment]
I'll take a look at this one

**Comment by LewisStaples** [comment]
The functionality for this issue is now complete (Dev postgres #112)
